### ISSUE TITLE
will not you backport mod to 1.16.5?

### ISSUE THREAD

**Issue by Nicknaem** [enjarai/do-a-barrel-roll#21] opened 2022-10-06 21:27 UTC
would be cool to use this mod in 1.16.5

**Comment by enjarai** [comment] 2022-10-07 20:05
This is planned, but there's currently a forge port in the works. I'd rather wait for that to be completed, as it will restructure the code significantly, rendering any prior backporting efforts mostly obsolete. 

Closing considering this is technically a duplicate of #11.

**Closed by enjarai** 2022-10-07 20:05 UTC
