### ISSUE TITLE
[SUGGESTION] Add a Config Option for Center of Gravity (and more)

### ISSUE THREAD

**Issue by Camawama** [enjarai/do-a-barrel-roll#44] opened 2022-12-28 04:01 UTC
-Ability to change the center of gravity 

-Better compatibility with other Elytra mods

-Optionally include the mod server-side to control parameters that would otherwise likely be used in malicious ways.

-Real-time Config updates

I know some of these things are difficult. I am just leaving ideas.

**Comment by enjarai** [comment] 2022-12-28 11:07
Center of gravity is quite a complex idea, how are you imagining this to work? And what do you mean by better compatibility? Are there any specific elytra mods that arent compatible currently that I don't know about?

**Comment by Camawama** [comment] 2022-12-28 14:40
There would be a config option for the center of gravity, it would be relative to the height of the player heigh possibly calculated in the measurement of blocks (0.0-2.0). Changing the center of gravity to 2 would move the center of gravity to the top of the player's head. Very high or low values can make flight unstable, but having the option to allow for fine-tune adjustments might help a player get the exact way of flying they are looking for.

You can reference this demonstration video for CG https://youtu.be/hPn_nLAauBw
I am not a professional, I just thought this could be an interesting idea.

When I said "better compatibility" I was more or less speaking about the thrust adjustments and such that are offered in the config. Certain elytra mods are created to help nerf elytra flight but allowing players to bypass said restrictions with a simple client-side configuration tweak is not ideal. 

I do apologize that I am bringing the same thing up multiple times. I hope you can understand that I love this mod so much and I just want it to be balanced in a way to prevent cheating on a public server.

**Comment by enjarai** [comment] 2022-12-28 18:26
From what I understand, the center of gravity would affect flight physics significantly, and create a more realistic experience. This is definitely out of scope for this mod. I don't have the in-depth knowhow required to apply the mathematics for it, and I want to keep core functionality compatible with vanilla servers.

When you say compatibility issues, this essentially boils down to a duplicate of #38 then? The conversation there might've gotten a bit off-topic, but the points I made still stand. 

While it does make cheating relatively accessible, it'd also be easy enough for end users to get around any barriers I put up around it. To add to that, the architecture this mod is based on, combined with my lack of understanding of Forge modding, makes it very difficult for me to implement a server-side off switch. So seeing as this is something I'm doing in my free time and because I enjoy doing it, the positives don't outweigh the time I'd have to spend.

If you or anyone else does want to spend that time, I'd gladly receive a PR to address the issues you raise, but I doubt I'll be doing it myself any time soon.

Aside from those topics, you also mention "Real-time Config updates". What exactly do you mean by that? It's already possible to edit the config ingame, which updates and applies instantly.

**Comment by Camawama** [comment] 2023-01-02 14:32
I will have to test out real-time config updates again. When I was modifying config in-game it didn't seem to do anything and the config file would duplicate with a copy of old config that the game was still using.

**Comment by enjarai** [comment] 2023-01-02 23:29
I've finally found the time to properly look into a server-side toggle for thrusting, and realised the main problem holding it back was getting it to work nicely with forge. Since the implementation would be rather easy with that part left out, I've temporarily completely removed thrusting on the forge version, and implemented a simple server-side toggle for the fabric version only.

This feature is available from 2.4.0 onwards, the README details how to use it. Keep the caveats I've mentioned in my earlier comments in mind though, this isn't a catch-all solution. I do hope that this will be of help for your server.

**Comment by Camawama** [comment] 2023-01-03 02:35
I cannot thank you enough for implementing this fix. I will be sure to update everything right away! 😃

**Comment by enjarai** [comment] 2023-01-05 09:26
Closing this, as it seems everything you mentioned is adressed. Feel free to open a new issue if there's anything else.

**Closed by enjarai** 2023-01-05 09:26 UTC
Labels: enhancement
